keys = {'If-Modified-Since': 'Wed, 21 Oct 2015 07:28:00 GMT'}

sample_board = {'board': '3', 'title': '3DCG', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
                'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
                'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
                'meta_description': "&quot;/3/ - 3DCG&quot; is 4chan's board for 3D modeling and imagery.",
                'is_archived': 1}

sample_thread = {
    "posts": [{
        "no": 570368,
        "sticky": 1,
        "closed": 1,
        "now": "12\/31\/18(Mon)17:05:48",
        "name": "Anonymous",
        "sub": "Welcome to \/po\/!",
        "com": "Welcome to \/po\/! We specialize in origami, papercraft, and everything that\u2019s relevant to paper engineering. This board is also an great library of relevant PDF books and instructions, one of the best resource of its kind on the internet.<br><br>Questions and discussions of papercraft and origami are welcome. Threads for topics covered by paper engineering in general are also welcome, such as kirigami, bookbinding, printing technology, sticker making, gift boxes, greeting cards, and more.<br><br>Requesting is permitted, even encouraged if it\u2019s a good request; fulfilled requests strengthens this board\u2019s role as a repository of books and instructions. However do try to keep requests in relevant threads, if you can.<br><br>\/po\/ is a slow board! Do not needlessly bump threads.",
        "filename": "yotsuba_folding",
        "ext": ".png",
        "w": 530,
        "h": 449,
        "tn_w": 250,
        "tn_h": 211,
        "tim": 1546293948883,
        "time": 1546293948,
        "md5": "uZUeZeB14FVR+Mc2ScHvVA==",
        "fsize": 516657,
        "resto": 0,
        "capcode": "mod",
        "semantic_url": "welcome-to-po",
        "replies": 2,
        "images": 2,
        "unique_ips": 1
    }, {
        "no": 570370,
        "now": "12\/31\/18(Mon)17:14:56",
        "name": "Anonymous",
        "com": "<b>FAQs about papercraft<\/b><br>\n<br>\n<i>What paper should I use?<\/i><br>\n<br>\nSmall models can be made with light 100 to 150 gsm paper, while large ones are better with heavy 150 to 200+ gsm paper.<br>\n<br>\n<i>Where do I begin with papercraft can I find easy papercrafts?<\/i><br>\n<br>\nPapercraft also requires glue, and cutting tools. A PVA glue stick is works. A pen knife and cutting board is recommended, but otherwise scissors are okay for simple models.<br>\n<br>\nPapercraft normally involves printing and cutting out a number of nets, and and gluing tabs and pieces where appropriate to form a model.<br>\n<br>\nYou can find a variety of papercraft models on this board that may interest you. Ask for some otherwise, and be specific about what you would like. You can search online for \u2018easy papercraft templates\u2019, these links have many.<br>\n<br>\n<a href=\"http:\/\/papercraft.wikidot.com\/papercraft\">http:\/\/papercraft.wikidot.com\/paper<wbr>craft<\/a><br>\n<a href=\"http:\/\/cp.c-ij.com\/en\/categories\/CAT-ST01-0071\/top.html\">http:\/\/cp.c-ij.com\/en\/categories\/CA<wbr>T-ST01-0071\/top.html<\/a><br>\n<br>\n<i>What is Pepakura?<\/i><br>\n<br>\nPepakura Designer is a program that takes 3D models and `unfolds&#039; them to papercraft templates. Using Pepakura in conjunction with a 3D modelling software, such as Blender, you can design your own papercraft models.<br>\n<br>\n<a href=\"https:\/\/elementcrafts.wordpress.com\/2014\/04\/22\/a-complete-beginners-guide-to-papercraft-pepakura-windows-only\/\">https:\/\/elementcrafts.wordpress.com<wbr>\/2014\/04\/22\/a-complete-beginners-gu<wbr>ide-to-papercraft-pepakura-windows-<wbr>only\/<\/a><br>\n<br>\n<i>Hints and tips?<\/i>\n<br>\nGlue accurately for a model to hold well, and practice plenty.<br>\n<br>\n<a href=\"http:\/\/www.papercraftmuseum.com\/advanced-tutorial\/\">http:\/\/www.papercraftmuseum.com\/adv<wbr>anced-tutorial\/<\/a><br>",
        "filename": "papercraft faq",
        "ext": ".png",
        "w": 318,
        "h": 704,
        "tn_w": 56,
        "tn_h": 125,
        "tim": 1546294496751,
        "time": 1546294496,
        "md5": "0EqXBb4gGIyzQiaApMdFAA==",
        "fsize": 285358,
        "resto": 570368,
        "capcode": "mod"
    }, {
        "no": 570371,
        "now": "12\/31\/18(Mon)17:21:29",
        "name": "Anonymous",
        "com": "<b>FAQs about origami<\/b><br>\n<br>\n<i>Where do I begin with origami and how can I find easy models?<\/i><br>\n<br>\nTry browsing the board for guides, or other online resources listed below, for models you like and practice folding them.<br>\n<br>\nA great way to begin at origami is to participate in the Let\u2019s Fold Together threads <a href=\"https:\/\/boards.4channel.org\/po\/catalog#s=lft\"><a href=\"\/\/boards.4channel.org\/po\/catalog#s=lft\" class=\"quotelink\">&gt;&gt;&gt;\/po\/lft<\/a><\/a> - open up the PDF file and find a model you like, work on it, and discuss or post results.<br>\n<br>\n<a href=\"http:\/\/en.origami-club.com\">http:\/\/en.origami-club.com<\/a><br>\n<a href=\"https:\/\/origami.me\/diagrams\/\">https:\/\/origami.me\/diagrams\/<\/a><br>\n<a href=\"https:\/\/www.origami-resource-center.com\/free-origami-instructions.html\">https:\/\/www.origami-resource-center<wbr>.com\/free-origami-instructions.html<wbr><\/a><br>\n<a href=\"http:\/\/www.paperfolding.com\/diagrams\/\">http:\/\/www.paperfolding.com\/diagram<wbr>s\/<\/a><br>\n<br>\n<i>What paper should I use?<\/i><br>\n<br>\nIt depends on the model; for smaller models which involved 25 steps or fewer, 15 by 15 cm origami paper from a local craft store will be suitable. For larger models you will need larger or thinner paper, possibly from online shops. Boxpleated models require thin paper, such as sketching paper. Wet folded models require thicker paper, such as elephant hide.<br>\n<br>\n<a href=\"https:\/\/www.origami-shop.com\/en\/\">https:\/\/www.origami-shop.com\/en\/<\/a><br>\n<br>\n<i>Hints and tips?<\/i><br>\n<br>\nFor folding, The best advice is to always fold as cleanly as possible, and take your time. Everything else comes with experience.<br>\n<br>\n<a href=\"https:\/\/origami.me\/beginners-guide\/\">https:\/\/origami.me\/beginners-guide\/<wbr><\/a><br>\n<a href=\"https:\/\/origamiusa.org\/glossary\">https:\/\/origamiusa.org\/glossary<\/a><br>\n<br>\n<i>What are \u2018CPs\u2019?<\/i><br>\n<br>\nCrease patterns are a structural representations of origami models, shown as a schematic of lines; they are essentially origami models unfolded and laid flat. Lines on a crease pattern may be indicated by \u2018mountain\u2019 or \u2018valley\u2019 folds to show how the folds alternate. If you\u2019re particularly skilled at origami, they become useful instructions for building models. A common base fold is usually discernable, all the intermediate details can be worked on from there.<br>\n<br>\n<a href=\"https:\/\/blog.giladnaor.com\/2008\/08\/folding-from-crease-patterns.html\">https:\/\/blog.giladnaor.com\/2008\/08\/<wbr>folding-from-crease-patterns.html<\/a><br>\n<a href=\"http:\/\/www.origamiaustria.at\/articles.php?lang=2#a4\">http:\/\/www.origamiaustria.at\/articl<wbr>es.php?lang=2#a4<\/a><br>",
        "filename": "origami faq",
        "ext": ".jpg",
        "w": 762,
        "h": 762,
        "tn_w": 125,
        "tn_h": 125,
        "tim": 1546294889019,
        "time": 1546294889,
        "md5": "vKWr7+oITdUBu7bUaypuCw==",
        "fsize": 163110,
        "resto": 570368,
        "capcode": "mod"
    }]
}
sample_thread_list = [{"page": 1, "threads": [{"no": 570368, "last_modified": 1546294897, "replies": 2},
                                              {"no": 579528, "last_modified": 1582194421, "replies": 0},
                                              {"no": 568476, "last_modified": 1582193036, "replies": 262},
                                              {"no": 578822, "last_modified": 1582166272, "replies": 14},
                                              {"no": 578465, "last_modified": 1582162041, "replies": 3},
                                              {"no": 546973, "last_modified": 1582140575, "replies": 126},
                                              {"no": 579441, "last_modified": 1582124885, "replies": 2},
                                              {"no": 579515, "last_modified": 1582113201, "replies": 0},
                                              {"no": 579400, "last_modified": 1582111182, "replies": 18},
                                              {"no": 578022, "last_modified": 1582110915, "replies": 18},
                                              {"no": 579486, "last_modified": 1582110555, "replies": 5},
                                              {"no": 577421, "last_modified": 1582067387, "replies": 24},
                                              {"no": 579102, "last_modified": 1582066688, "replies": 40},
                                              {"no": 578405, "last_modified": 1582049669, "replies": 13},
                                              {"no": 579470, "last_modified": 1581978752, "replies": 5}]}, {"page": 2,
                                                                                                            "threads": [
                                                                                                                {
                                                                                                                    "no": 578375,
                                                                                                                    "last_modified": 1581977975,
                                                                                                                    "replies": 12},
                                                                                                                {
                                                                                                                    "no": 579446,
                                                                                                                    "last_modified": 1581957533,
                                                                                                                    "replies": 4},
                                                                                                                {
                                                                                                                    "no": 553409,
                                                                                                                    "last_modified": 1581952554,
                                                                                                                    "replies": 296},
                                                                                                                {
                                                                                                                    "no": 578454,
                                                                                                                    "last_modified": 1581851717,
                                                                                                                    "replies": 1},
                                                                                                                {
                                                                                                                    "no": 539829,
                                                                                                                    "last_modified": 1581827322,
                                                                                                                    "replies": 255},
                                                                                                                {
                                                                                                                    "no": 579272,
                                                                                                                    "last_modified": 1581825112,
                                                                                                                    "replies": 5},
                                                                                                                {
                                                                                                                    "no": 559513,
                                                                                                                    "last_modified": 1581804025,
                                                                                                                    "replies": 165},
                                                                                                                {
                                                                                                                    "no": 554084,
                                                                                                                    "last_modified": 1581797532,
                                                                                                                    "replies": 269},
                                                                                                                {
                                                                                                                    "no": 579320,
                                                                                                                    "last_modified": 1581754641,
                                                                                                                    "replies": 7},
                                                                                                                {
                                                                                                                    "no": 568362,
                                                                                                                    "last_modified": 1581736704,
                                                                                                                    "replies": 57},
                                                                                                                {
                                                                                                                    "no": 564774,
                                                                                                                    "last_modified": 1581705306,
                                                                                                                    "replies": 148},
                                                                                                                {
                                                                                                                    "no": 566305,
                                                                                                                    "last_modified": 1581688042,
                                                                                                                    "replies": 120},
                                                                                                                {
                                                                                                                    "no": 547797,
                                                                                                                    "last_modified": 1581685770,
                                                                                                                    "replies": 79},
                                                                                                                {
                                                                                                                    "no": 579418,
                                                                                                                    "last_modified": 1581704067,
                                                                                                                    "replies": 0},
                                                                                                                {
                                                                                                                    "no": 574188,
                                                                                                                    "last_modified": 1581704077,
                                                                                                                    "replies": 63}]},
                      {"page": 3, "threads": [{"no": 579392, "last_modified": 1581639091, "replies": 3},
                                              {"no": 566458, "last_modified": 1581527692, "replies": 111},
                                              {"no": 579389, "last_modified": 1581513183, "replies": 0},
                                              {"no": 578021, "last_modified": 1581503880, "replies": 6},
                                              {"no": 579317, "last_modified": 1581448690, "replies": 13},
                                              {"no": 576837, "last_modified": 1581313252, "replies": 17},
                                              {"no": 544995, "last_modified": 1581312682, "replies": 73},
                                              {"no": 576112, "last_modified": 1581245361, "replies": 74},
                                              {"no": 579049, "last_modified": 1581240675, "replies": 3},
                                              {"no": 578192, "last_modified": 1581215765, "replies": 1},
                                              {"no": 571044, "last_modified": 1581153368, "replies": 28},
                                              {"no": 579006, "last_modified": 1581091887, "replies": 3},
                                              {"no": 579259, "last_modified": 1581031088, "replies": 42},
                                              {"no": 578119, "last_modified": 1581022538, "replies": 4},
                                              {"no": 579182, "last_modified": 1581013743, "replies": 5}]}, {"page": 4,
                                                                                                            "threads": [
                                                                                                                {
                                                                                                                    "no": 569063,
                                                                                                                    "last_modified": 1580974522,
                                                                                                                    "replies": 77},
                                                                                                                {
                                                                                                                    "no": 578923,
                                                                                                                    "last_modified": 1580895504,
                                                                                                                    "replies": 4},
                                                                                                                {
                                                                                                                    "no": 577654,
                                                                                                                    "last_modified": 1580891389,
                                                                                                                    "replies": 4},
                                                                                                                {
                                                                                                                    "no": 579237,
                                                                                                                    "last_modified": 1580855394,
                                                                                                                    "replies": 4},
                                                                                                                {
                                                                                                                    "no": 578351,
                                                                                                                    "last_modified": 1580767791,
                                                                                                                    "replies": 4},
                                                                                                                {
                                                                                                                    "no": 535361,
                                                                                                                    "last_modified": 1580763681,
                                                                                                                    "replies": 239},
                                                                                                                {
                                                                                                                    "no": 578889,
                                                                                                                    "last_modified": 1580652093,
                                                                                                                    "replies": 8},
                                                                                                                {
                                                                                                                    "no": 578773,
                                                                                                                    "last_modified": 1580619095,
                                                                                                                    "replies": 2},
                                                                                                                {
                                                                                                                    "no": 576972,
                                                                                                                    "last_modified": 1580598979,
                                                                                                                    "replies": 39},
                                                                                                                {
                                                                                                                    "no": 572890,
                                                                                                                    "last_modified": 1580580086,
                                                                                                                    "replies": 69},
                                                                                                                {
                                                                                                                    "no": 579172,
                                                                                                                    "last_modified": 1580450040,
                                                                                                                    "replies": 2},
                                                                                                                {
                                                                                                                    "no": 577135,
                                                                                                                    "last_modified": 1580442508,
                                                                                                                    "replies": 4},
                                                                                                                {
                                                                                                                    "no": 579192,
                                                                                                                    "last_modified": 1580270586,
                                                                                                                    "replies": 0},
                                                                                                                {
                                                                                                                    "no": 579177,
                                                                                                                    "last_modified": 1580196202,
                                                                                                                    "replies": 1},
                                                                                                                {
                                                                                                                    "no": 579167,
                                                                                                                    "last_modified": 1580060853,
                                                                                                                    "replies": 2}]},
                      {"page": 5, "threads": [{"no": 578849, "last_modified": 1580010755, "replies": 2},
                                              {"no": 575402, "last_modified": 1580004484, "replies": 13},
                                              {"no": 579128, "last_modified": 1579955748, "replies": 3},
                                              {"no": 575679, "last_modified": 1579770002, "replies": 8},
                                              {"no": 579071, "last_modified": 1579748437, "replies": 2},
                                              {"no": 577772, "last_modified": 1579746100, "replies": 2},
                                              {"no": 577148, "last_modified": 1579713891, "replies": 13},
                                              {"no": 568307, "last_modified": 1579654271, "replies": 35},
                                              {"no": 567826, "last_modified": 1579650409, "replies": 28},
                                              {"no": 561868, "last_modified": 1579623985, "replies": 47},
                                              {"no": 560137, "last_modified": 1579614173, "replies": 51},
                                              {"no": 544301, "last_modified": 1579614111, "replies": 139},
                                              {"no": 579027, "last_modified": 1579507194, "replies": 2},
                                              {"no": 577040, "last_modified": 1579468461, "replies": 5},
                                              {"no": 578116, "last_modified": 1579407233, "replies": 29}]}, {"page": 6,
                                                                                                             "threads": [
                                                                                                                 {
                                                                                                                     "no": 579035,
                                                                                                                     "last_modified": 1579376295,
                                                                                                                     "replies": 2},
                                                                                                                 {
                                                                                                                     "no": 579042,
                                                                                                                     "last_modified": 1579283693,
                                                                                                                     "replies": 2},
                                                                                                                 {
                                                                                                                     "no": 579029,
                                                                                                                     "last_modified": 1579170149,
                                                                                                                     "replies": 1},
                                                                                                                 {
                                                                                                                     "no": 545554,
                                                                                                                     "last_modified": 1579117905,
                                                                                                                     "replies": 186},
                                                                                                                 {
                                                                                                                     "no": 579019,
                                                                                                                     "last_modified": 1579097806,
                                                                                                                     "replies": 1},
                                                                                                                 {
                                                                                                                     "no": 579018,
                                                                                                                     "last_modified": 1579066740,
                                                                                                                     "replies": 0},
                                                                                                                 {
                                                                                                                     "no": 569358,
                                                                                                                     "last_modified": 1579062868,
                                                                                                                     "replies": 24},
                                                                                                                 {
                                                                                                                     "no": 578685,
                                                                                                                     "last_modified": 1579040336,
                                                                                                                     "replies": 7},
                                                                                                                 {
                                                                                                                     "no": 577843,
                                                                                                                     "last_modified": 1579026092,
                                                                                                                     "replies": 2},
                                                                                                                 {
                                                                                                                     "no": 579007,
                                                                                                                     "last_modified": 1579023210,
                                                                                                                     "replies": 1},
                                                                                                                 {
                                                                                                                     "no": 573953,
                                                                                                                     "last_modified": 1579116277,
                                                                                                                     "replies": 14},
                                                                                                                 {
                                                                                                                     "no": 568442,
                                                                                                                     "last_modified": 1578980371,
                                                                                                                     "replies": 21},
                                                                                                                 {
                                                                                                                     "no": 577871,
                                                                                                                     "last_modified": 1578964485,
                                                                                                                     "replies": 1},
                                                                                                                 {
                                                                                                                     "no": 578936,
                                                                                                                     "last_modified": 1578961091,
                                                                                                                     "replies": 2},
                                                                                                                 {
                                                                                                                     "no": 578940,
                                                                                                                     "last_modified": 1578954544,
                                                                                                                     "replies": 3}]},
                      {"page": 7, "threads": [{"no": 577804, "last_modified": 1578940227, "replies": 3},
                                              {"no": 577653, "last_modified": 1578940223, "replies": 5},
                                              {"no": 577754, "last_modified": 1578940222, "replies": 1},
                                              {"no": 577764, "last_modified": 1578940221, "replies": 2},
                                              {"no": 575980, "last_modified": 1578906187, "replies": 3},
                                              {"no": 577171, "last_modified": 1578940224, "replies": 11},
                                              {"no": 539494, "last_modified": 1579381042, "replies": 114},
                                              {"no": 578948, "last_modified": 1578883710, "replies": 0},
                                              {"no": 578939, "last_modified": 1578878980, "replies": 1},
                                              {"no": 578931, "last_modified": 1578795755, "replies": 1},
                                              {"no": 573328, "last_modified": 1578769465, "replies": 45},
                                              {"no": 577422, "last_modified": 1578719801, "replies": 9},
                                              {"no": 568695, "last_modified": 1578685023, "replies": 42},
                                              {"no": 578877, "last_modified": 1578663984, "replies": 5},
                                              {"no": 571273, "last_modified": 1578661539, "replies": 151}]}, {"page": 8,
                                                                                                              "threads": [
                                                                                                                  {
                                                                                                                      "no": 577525,
                                                                                                                      "last_modified": 1578624791,
                                                                                                                      "replies": 7},
                                                                                                                  {
                                                                                                                      "no": 578506,
                                                                                                                      "last_modified": 1578539250,
                                                                                                                      "replies": 3},
                                                                                                                  {
                                                                                                                      "no": 577154,
                                                                                                                      "last_modified": 1578535888,
                                                                                                                      "replies": 6},
                                                                                                                  {
                                                                                                                      "no": 578854,
                                                                                                                      "last_modified": 1578500321,
                                                                                                                      "replies": 1},
                                                                                                                  {
                                                                                                                      "no": 578828,
                                                                                                                      "last_modified": 1578334299,
                                                                                                                      "replies": 2},
                                                                                                                  {
                                                                                                                      "no": 552867,
                                                                                                                      "last_modified": 1578291495,
                                                                                                                      "replies": 222},
                                                                                                                  {
                                                                                                                      "no": 578368,
                                                                                                                      "last_modified": 1578290310,
                                                                                                                      "replies": 4},
                                                                                                                  {
                                                                                                                      "no": 577158,
                                                                                                                      "last_modified": 1578231195,
                                                                                                                      "replies": 3},
                                                                                                                  {
                                                                                                                      "no": 577153,
                                                                                                                      "last_modified": 1578225667,
                                                                                                                      "replies": 6},
                                                                                                                  {
                                                                                                                      "no": 578778,
                                                                                                                      "last_modified": 1578044098,
                                                                                                                      "replies": 1},
                                                                                                                  {
                                                                                                                      "no": 575555,
                                                                                                                      "last_modified": 1579299569,
                                                                                                                      "replies": 14},
                                                                                                                  {
                                                                                                                      "no": 557105,
                                                                                                                      "last_modified": 1578010890,
                                                                                                                      "replies": 30},
                                                                                                                  {
                                                                                                                      "no": 576718,
                                                                                                                      "last_modified": 1577846662,
                                                                                                                      "replies": 7},
                                                                                                                  {
                                                                                                                      "no": 578741,
                                                                                                                      "last_modified": 1577802892,
                                                                                                                      "replies": 0},
                                                                                                                  {
                                                                                                                      "no": 578739,
                                                                                                                      "last_modified": 1577787651,
                                                                                                                      "replies": 0}]},
                      {"page": 9, "threads": [{"no": 577770, "last_modified": 1577713865, "replies": 4},
                                              {"no": 578660, "last_modified": 1577611434, "replies": 4},
                                              {"no": 577524, "last_modified": 1577609962, "replies": 6},
                                              {"no": 546816, "last_modified": 1577573540, "replies": 117},
                                              {"no": 578390, "last_modified": 1577567427, "replies": 8},
                                              {"no": 575795, "last_modified": 1577480119, "replies": 6},
                                              {"no": 578680, "last_modified": 1577432591, "replies": 2},
                                              {"no": 578531, "last_modified": 1577342558, "replies": 3},
                                              {"no": 578586, "last_modified": 1577239887, "replies": 2},
                                              {"no": 568978, "last_modified": 1577230600, "replies": 11},
                                              {"no": 558164, "last_modified": 1577219900, "replies": 29},
                                              {"no": 573494, "last_modified": 1577219790, "replies": 6},
                                              {"no": 557466, "last_modified": 1577219900, "replies": 15},
                                              {"no": 563744, "last_modified": 1577219790, "replies": 39},
                                              {"no": 547093, "last_modified": 1577219790, "replies": 125}]},
                      {"page": 10,
                       "threads": [{
                           "no": 555961,
                           "last_modified": 1577219790,
                           "replies": 37},
                           {
                               "no": 567514,
                               "last_modified": 1577217460,
                               "replies": 21},
                           {
                               "no": 578372,
                               "last_modified": 1577206822,
                               "replies": 4},
                           {
                               "no": 577777,
                               "last_modified": 1577118976,
                               "replies": 4},
                           {
                               "no": 559123,
                               "last_modified": 1577219900,
                               "replies": 134},
                           {
                               "no": 575972,
                               "last_modified": 1576901641,
                               "replies": 3},
                           {
                               "no": 578537,
                               "last_modified": 1576787404,
                               "replies": 0},
                           {
                               "no": 578521,
                               "last_modified": 1576682512,
                               "replies": 0},
                           {
                               "no": 578148,
                               "last_modified": 1576427258,
                               "replies": 14},
                           {
                               "no": 578289,
                               "last_modified": 1576283537,
                               "replies": 7},
                           {
                               "no": 578428,
                               "last_modified": 1576259128,
                               "replies": 0},
                           {
                               "no": 578211,
                               "last_modified": 1576221964,
                               "replies": 9},
                           {
                               "no": 578083,
                               "last_modified": 1576033041,
                               "replies": 7},
                           {
                               "no": 578359,
                               "last_modified": 1575902849,
                               "replies": 0},
                           {
                               "no": 577888,
                               "last_modified": 1575775146,
                               "replies": 2}]},
                      {"page": 11, "threads": [{"no": 577076, "last_modified": 1575664269, "replies": 4}]}]

boards = {'boards': [
    {'board': 'c3', 'title': '3DCG', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/3/ - 3DCG&quot; is 4chan's board for 3D modeling and imagery.", 'is_archived': 1},
    {'board': 'a', 'title': 'Anime & Manga', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 500,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/a/ - Anime &amp; Manga&quot; is 4chan's imageboard dedicated to the discussion of Japanese animation and manga.",
     'spoilers': 1, 'custom_spoilers': 1, 'is_archived': 1},
    {'board': 'aco', 'title': 'Adult Cartoons', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/aco/ - Adult Cartoons&quot; is 4chan's imageboard for posting western-styled adult cartoon artwork.",
     'is_archived': 1},
    {'board': 'adv', 'title': 'Advice', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/adv/ - Advice&quot; is 4chan's board for giving and receiving advice. ",
     'is_archived': 1},
    {'board': 'an', 'title': 'Animals & Nature', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/an/ - Animals &amp; Nature&quot; is 4chan's imageboard for posting pictures of animals, pets, and nature.",
     'is_archived': 1},
    {'board': 'asp', 'title': 'Alternative Sports & Wrestling', 'ws_board': 1, 'per_page': 15, 'pages': 10,
     'max_filesize': 4194304, 'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120,
     'bump_limit': 310, 'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/asp/ - Alternative Sports &amp; Wrestling&quot; is 4chan's imageboard for the discussion of alternative and extreme sports such as wrestling and paintball.",
     'is_archived': 1},
    {'board': 'b', 'title': 'Random', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 2097152,
     'max_webm_filesize': 2097152, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 150, 'cooldowns': {'threads': 60, 'replies': 15, 'images': 15},
     'meta_description': '&quot;/b/ - Random&quot; is the birthplace of Anonymous, and where people go to discuss random topics and create memes on 4chan.',
     'forced_anon': 1}, {'board': 'bant', 'title': 'International/Random', 'ws_board': 0, 'per_page': 15, 'pages': 10,
                         'max_filesize': 2097152, 'max_webm_filesize': 2097152, 'max_comment_chars': 2000,
                         'max_webm_duration': 120, 'bump_limit': 300, 'image_limit': 150,
                         'cooldowns': {'threads': 60, 'replies': 15, 'images': 15},
                         'meta_description': "&quot;/bant/ - International/Random&quot; is 4chan's international hanging out board, where you can have fun with Anonymous all over the world.",
                         'user_ids': 1, 'country_flags': 1},
    {'board': 'biz', 'title': 'Business & Finance', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/biz/ - Business &amp; Finance&quot; is 4chan's imageboard for the discussion of business and finance, and cryptocurrencies such as Bitcoin and Dogecoin.",
     'user_ids': 1, 'is_archived': 1},
    {'board': 'c', 'title': 'Anime/Cute', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/c/ - Anime/Cute&quot; is 4chan's imageboard for cute and moe anime images.",
     'is_archived': 1},
    {'board': 'cgl', 'title': 'Cosplay & EGL', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/cgl/ - Cosplay &amp; EGL&quot; is 4chan's imageboard for the discussion of cosplay, elegant gothic lolita (EGL), and anime conventions.",
     'is_archived': 1},
    {'board': 'ck', 'title': 'Food & Cooking', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/ck/ - Food &amp; Cooking&quot; is 4chan's imageboard for food pictures and cooking recipes.",
     'is_archived': 1},
    {'board': 'cm', 'title': 'Cute/Male', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/cm/ - Cute/Male&quot; is 4chan's imageboard for posting pictures of cute anime males.",
     'is_archived': 1},
    {'board': 'co', 'title': 'Comics & Cartoons', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 500,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/co/ - Comics &amp; Cartoons&quot; is 4chan's imageboard dedicated to the discussion of Western cartoons and comics.",
     'spoilers': 1, 'custom_spoilers': 5, 'is_archived': 1},
    {'board': 'd', 'title': 'Hentai/Alternative', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/d/ - Hentai/Alternative&quot; is 4chan's imageboard for alternative hentai images.",
     'is_archived': 1},
    {'board': 'diy', 'title': 'Do It Yourself', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/diy/ - Do It Yourself&quot; is 4chan's imageboard for DIY/do it yourself projects, home improvement, and makers.",
     'is_archived': 1},
    {'board': 'e', 'title': 'Ecchi', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/e/ - Ecchi&quot; is 4chan's imageboard for suggestive (ecchi) hentai images.",
     'is_archived': 1},
    {'board': 'f', 'title': 'Flash', 'ws_board': 0, 'per_page': 30, 'pages': 1, 'max_filesize': 10485760,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/f/ - Flash&quot; is 4chan's upload board for sharing Adobe Flash files (SWFs)."},
    {'board': 'fa', 'title': 'Fashion', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/fa/ - Fashion&quot; is 4chan's imageboard for images and discussion relating to fashion and apparel.",
     'is_archived': 1},
    {'board': 'fit', 'title': 'Fitness', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/fit/ - Fitness&quot; is 4chan's imageboard for weightlifting, health, and fitness.",
     'is_archived': 1},
    {'board': 'g', 'title': 'Technology', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/g/ - Technology&quot; is 4chan's imageboard for discussing computer hardware and software, programming, and general technology.",
     'is_archived': 1, 'code_tags': 1},
    {'board': 'gd', 'title': 'Graphic Design', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 8388608,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/gd/ - Graphic Design&quot; is 4chan's imageboard for graphic design.",
     'is_archived': 1},
    {'board': 'gif', 'title': 'Adult GIF', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 4194304, 'max_comment_chars': 2000, 'max_webm_duration': 300, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/gif/ - Adult GIF&quot; is 4chan's imageboard dedicated to animated adult GIFs and WEBMs.",
     'is_archived': 1, 'webm_audio': 1},
    {'board': 'h', 'title': 'Hentai', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/h/ - Hentai&quot; is 4chan's imageboard for adult Japanese anime hentai images.",
     'is_archived': 1},
    {'board': 'hc', 'title': 'Hardcore', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 8388608,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/hc/ - Hardcore&quot; is 4chan's imageboard for the posting of adult hardcore pornography.",
     'is_archived': 1, 'min_image_width': 500, 'min_image_height': 500},
    {'board': 'his', 'title': 'History & Humanities', 'ws_board': 1, 'per_page': 15, 'pages': 10,
     'max_filesize': 4194304, 'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120,
     'bump_limit': 310, 'image_limit': 150, 'cooldowns': {'threads': 60, 'replies': 15, 'images': 15},
     'meta_description': "&quot;/his/ - History &amp; Humanities&quot; is 4chan's board for discussing and debating history.",
     'is_archived': 1},
    {'board': 'hm', 'title': 'Handsome Men', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 8388608,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/hm/ - Handsome Men&quot; is 4chan's imageboard dedicated to sharing adult images of handsome men.",
     'is_archived': 1},
    {'board': 'hr', 'title': 'High Resolution', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 8388608,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/hr/ - High Resolution&quot; is 4chan's imageboard for the sharing of high resolution images.",
     'is_archived': 1, 'min_image_width': 1000, 'min_image_height': 1000},
    {'board': 'i', 'title': 'Oekaki', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/i/ - Oekaki&quot; is 4chan's oekaki board for drawing and sharing art.",
     'is_archived': 1, 'oekaki': 1},
    {'board': 'ic', 'title': 'Artwork/Critique', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/ic/ - Artwork/Critique&quot; is 4chan's imageboard for the discussion and critique of art.",
     'is_archived': 1},
    {'board': 'int', 'title': 'International', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/int/ - International&quot; is 4chan's international board, for the exchange of foreign language and culture.",
     'is_archived': 1, 'country_flags': 1},
    {'board': 'jp', 'title': 'Otaku Culture', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 5000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 300, 'cooldowns': {'threads': 3600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/jp/ - Otaku Culture&quot; is 4chan's board for discussing Japanese otaku culture.",
     'spoilers': 1, 'custom_spoilers': 1, 'is_archived': 1, 'sjis_tags': 1},
    {'board': 'k', 'title': 'Weapons', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/k/ - Weapons&quot; is 4chan's imageboard for discussing all types of weaponry, from military tanks to guns and knives.",
     'is_archived': 1},
    {'board': 'lgbt', 'title': 'LGBT', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/lgbt/ - LGBT&quot; is 4chan's imageboard for Lesbian-Gay-Bisexual-Transgender-Queer and sexuality discussion.",
     'is_archived': 1},
    {'board': 'lit', 'title': 'Literature', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 3000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/lit/ - Literature&quot; is 4chan's board for the discussion of books, authors, and literature.",
     'spoilers': 1, 'custom_spoilers': 1, 'is_archived': 1},
    {'board': 'm', 'title': 'Mecha', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/m/ - Mecha&quot; is 4chan's imageboard for discussing Japanese mecha robots and anime, like Gundam and Macross.",
     'spoilers': 1, 'custom_spoilers': 4, 'is_archived': 1},
    {'board': 'mlp', 'title': 'Pony', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 500,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/mlp/ - Pony&quot; is 4chan's imageboard dedicated to the discussion of My Little Pony: Friendship is Magic.",
     'spoilers': 1, 'custom_spoilers': 1, 'is_archived': 1},
    {'board': 'mu', 'title': 'Music', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/mu/ - Music&quot; is 4chan's imageboard for discussing all types of music.",
     'is_archived': 1},
    {'board': 'n', 'title': 'Transportation', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/n/ - Transportation&quot; is 4chan's imageboard for discussing modes of transportation like trains and bicycles.",
     'is_archived': 1},
    {'board': 'news', 'title': 'Current News', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 500,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/news/ - Current News; is 4chan's board for current news. ", 'spoilers': 1,
     'custom_spoilers': 1, 'is_archived': 1, 'text_only': 1, 'require_subject': 1},
    {'board': 'o', 'title': 'Auto', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/o/ - Auto&quot; is 4chan's imageboard for discussing cars and motorcycles.",
     'is_archived': 1},
    {'board': 'out', 'title': 'Outdoors', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 5242880,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/out/ - Outdoors&quot; is 4chan's imageboard for discussing survivalist skills and outdoor activities such as hiking.",
     'is_archived': 1},
    {'board': 'p', 'title': 'Photography', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 5242880,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/p/ - Photography&quot; is 4chan's imageboard for sharing and critiquing photos.",
     'is_archived': 1}, {'board': 'po', 'title': 'Papercraft & Origami', 'ws_board': 1, 'per_page': 15, 'pages': 10,
                         'max_filesize': 8388608, 'max_webm_filesize': 3145728, 'max_comment_chars': 2000,
                         'max_webm_duration': 120, 'bump_limit': 310, 'image_limit': 150,
                         'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
                         'meta_description': "&quot;/po/ - Papercraft &amp; Origami&quot; is 4chan's imageboard for posting papercraft and origami templates and instructions.",
                         'is_archived': 1},
    {'board': 'pol', 'title': 'Politically Incorrect', 'ws_board': 0, 'per_page': 20, 'pages': 10,
     'max_filesize': 4194304, 'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120,
     'bump_limit': 300, 'image_limit': 300, 'cooldowns': {'threads': 60, 'replies': 15, 'images': 15},
     'meta_description': "&quot;/pol/ - Politically Incorrect&quot; is 4chan's board for discussing and debating politics and current events.",
     'user_ids': 1, 'is_archived': 1, 'troll_flags': 1},
    {'board': 'qa', 'title': 'Question & Answer', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/qa/ - Question &amp; Answer&quot; is 4chan's imageboard for question and answer threads.",
     'is_archived': 1},
    {'board': 'qst', 'title': 'Quests', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 8388608,
     'max_webm_filesize': 3145728, 'max_comment_chars': 3000, 'max_webm_duration': 120, 'bump_limit': 750,
     'image_limit': 375, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/qst/ - Quests&quot; is 4chan's imageboard for grinding XP.", 'spoilers': 1,
     'user_ids': 1, 'is_archived': 1, 'require_subject': 1, 'oekaki': 1},
    {'board': 'r', 'title': 'Adult Requests', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 8388608,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/r/ - Request&quot; is 4chan's imageboard dedicated to fulfilling all types of user requests.",
     'is_archived': 1, 'webm_audio': 1},
    {'board': 'r9k', 'title': 'ROBOT9001', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 2097152,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 500,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': '&quot;/r9k/ - ROBOT9001&quot; is a board for hanging out and posting greentext stories.',
     'spoilers': 1, 'is_archived': 1},
    {'board': 's', 'title': 'Sexy Beautiful Women', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 8388608,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/s/ - Sexy Beautiful Women&quot; is 4chan's imageboard dedicated to sharing images of softcore pornography.",
     'is_archived': 1, 'min_image_width': 500, 'min_image_height': 500},
    {'board': 's4s', 'title': 'Shit 4chan Says', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 2097152,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 300, 'replies': 60, 'images': 30},
     'meta_description': "&quot;[s4s] - Shit 4chan Says&quot; is 4chan's imageboard for posting dank memes :^)",
     'spoilers': 1, 'custom_spoilers': 6, 'is_archived': 1},
    {'board': 'sci', 'title': 'Science & Math', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/sci/ - Science &amp; Math&quot; is 4chan's board for the discussion of science and math.",
     'is_archived': 1, 'math_tags': 1},
    {'board': 'soc', 'title': 'Cams & Meetups', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 5242880,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 500,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/soc/ - Cams &amp; Meetups&quot; is 4chan's board for camwhores and meetups.",
     'user_ids': 1, 'is_archived': 1, 'forced_anon': 1},
    {'board': 'sp', 'title': 'Sports', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 500,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/sp/ - Sports&quot; is 4chan's imageboard for sports discussion.", 'is_archived': 1,
     'country_flags': 1},
    {'board': 't', 'title': 'Torrents', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/t/ - Torrents&quot; is 4chan's imageboard for posting links and descriptions to torrents.",
     'is_archived': 1},
    {'board': 'tg', 'title': 'Traditional Games', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 8388608,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/tg/ - Traditional Games&quot; is 4chan's imageboard for discussing traditional gaming, such as board games and tabletop RPGs.",
     'spoilers': 1, 'custom_spoilers': 2, 'is_archived': 1},
    {'board': 'toy', 'title': 'Toys', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/toy/ - Toys&quot; is 4chan's imageboard for talking about all kinds of toys!",
     'is_archived': 1},
    {'board': 'trash', 'title': 'Off-Topic', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/trash/ - Off-topic&quot; is 4chan's imageboard jail for off-topic threads.",
     'forced_anon': 1},
    {'board': 'trv', 'title': 'Travel', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 8388608,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/trv/ - Travel&quot; is 4chan's imageboard dedicated to travel and the countries of the world.",
     'is_archived': 1},
    {'board': 'tv', 'title': 'Television & Film', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/tv/ - Television &amp; Film&quot; is 4chan's imageboard dedicated to the discussion of television and film.",
     'spoilers': 1, 'custom_spoilers': 5, 'is_archived': 1},
    {'board': 'u', 'title': 'Yuri', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/u/ - Yuri&quot; is 4chan's imageboard for yuri hentai images.", 'spoilers': 1,
     'is_archived': 1},
    {'board': 'v', 'title': 'Video Games', 'ws_board': 1, 'per_page': 20, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 500,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/v/ - Video Games&quot; is 4chan's imageboard dedicated to the discussion of PC and console video games.",
     'spoilers': 1, 'custom_spoilers': 1, 'is_archived': 1},
    {'board': 'vg', 'title': 'Video Game Generals', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 750,
     'image_limit': 375, 'cooldowns': {'threads': 600, 'replies': 90, 'images': 120},
     'meta_description': "&quot;/vg/ - Video Game Generals&quot; is 4chan's imageboard dedicated to the discussion of PC and console video games.",
     'spoilers': 1, 'custom_spoilers': 1, 'is_archived': 1, 'require_subject': 1},
    {'board': 'vip', 'title': 'Very Important Posts', 'ws_board': 1, 'per_page': 15, 'pages': 10,
     'max_filesize': 4194304, 'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120,
     'bump_limit': 300, 'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/vip/ - Very Important Posts&quot; is 4chan's imageboard for Pass users.",
     'spoilers': 1, 'is_archived': 1, 'sjis_tags': 1, 'oekaki': 1},
    {'board': 'vp', 'title': 'Pokémon', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/vp/ - Pok&eacute;mon&quot; is 4chan's imageboard dedicated to discussing the Pok&eacute;mon series of video games and shows.",
     'spoilers': 1, 'custom_spoilers': 1, 'is_archived': 1},
    {'board': 'vr', 'title': 'Retro Games', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 500,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/vr/ - Retro Games&quot; is 4chan's imageboard for discussing retro console video games and classic arcade games.",
     'spoilers': 1, 'custom_spoilers': 2, 'is_archived': 1},
    {'board': 'w', 'title': 'Anime/Wallpapers', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 6291456,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/w/ - Anime/Wallpapers&quot; is 4chan's imageboard for posting Japanese anime wallpapers.",
     'is_archived': 1, 'min_image_width': 480, 'min_image_height': 600},
    {'board': 'wg', 'title': 'Wallpapers/General', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 6291456,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/wg/ - Wallpapers/General&quot; is 4chan's imageboard for posting general wallpapers.",
     'is_archived': 1, 'min_image_width': 480, 'min_image_height': 600},
    {'board': 'wsg', 'title': 'Worksafe GIF', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 6291456,
     'max_webm_filesize': 6291456, 'max_comment_chars': 2000, 'max_webm_duration': 300, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/wsg/ - Worksafe GIF&quot; is 4chan's imageboard dedicated to sharing worksafe animated GIFs and WEBMs.",
     'is_archived': 1, 'webm_audio': 1},
    {'board': 'wsr', 'title': 'Worksafe Requests', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 8388608,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/wsr/ - Worksafe Requests&quot; is 4chan's imageboard dedicated to fulfilling non-NSFW requests.",
     'is_archived': 1, 'webm_audio': 1},
    {'board': 'x', 'title': 'Paranormal', 'ws_board': 1, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 310,
     'image_limit': 150, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 60},
     'meta_description': "&quot;/x/ - Paranormal&quot; is 4chan's imageboard for the discussion of paranormal, spooky pictures and conspiracy theories.",
     'is_archived': 1},
    {'board': 'y', 'title': 'Yaoi', 'ws_board': 0, 'per_page': 15, 'pages': 10, 'max_filesize': 4194304,
     'max_webm_filesize': 3145728, 'max_comment_chars': 2000, 'max_webm_duration': 120, 'bump_limit': 300,
     'image_limit': 300, 'cooldowns': {'threads': 600, 'replies': 60, 'images': 30},
     'meta_description': "&quot;/y/ - Yaoi&quot; is 4chan's imageboard for posting adult yaoi hentai images.",
     'is_archived': 1}],
    'troll_flags': {'AC': 'Anarcho-Capitalist', 'AN': 'Anarchist', 'BL': 'Black Nationalist', 'CF': 'Confederate',
                    'CM': 'Communist', 'CT': 'Catalonia', 'DM': 'Democrat', 'EU': 'European', 'FC': 'Fascist',
                    'GN': 'Gadsden', 'GY': 'Gay', 'JH': 'Jihadi', 'KN': 'Kekistani', 'MF': 'Muslim',
                    'NB': 'National Bolshevik', 'NZ': 'Nazi', 'PC': 'Hippie', 'PR': 'Pirate', 'RE': 'Republican',
                    'TM': 'Templar', 'TR': 'Tree Hugger', 'UN': 'United Nations', 'WP': 'White Supremacist'}}
